### ISSUE TITLE
setting output flag for `linkml-data2owl` to a .ttl still yields a .ofn format

### ISSUE THREAD

**Issue by capsulecorplab** [linkml/linkml-owl#25]
Usage documentation as per https://linkml.io/linkml-owl/usage/#usage
```
linkml-data2owl -s my_schema.yaml my_data.{yaml,json,tsv,rdf} -o my_ontology.owl.ttl
```
still generates a file with .ofn syntax, as opposed to turtle syntax

**Comment by capsulecorplab** [comment]
My guess is that the documentation just has a typo and it meant to `my_ontology.owl.ofn` as opposed to `my_ontology.owl.ttl`, as the help text from `linkml-data2owl` doesn't seem to suggest it supports converting to turtle

**Comment by nlharris** [comment]
that sounds plausible
