### ISSUE TITLE
owl to linkml

### ISSUE THREAD

**Issue by joylix** [linkml/linkml-owl#30]
Can owl or rdf files be converted to linkml files, and how?

**Comment by turbomam** [comment]
I assume you're asking about converting an OWL representation of a schema to a LinkML schema. _(LinkML also provides tools for converting an RDF dataset into other formats, as long as the input dataset is valid against a LinkML schema.)_

You can convert an OWL schema/ontology into LinkML with the [`schemauto import-owl`](https://linkml.io/schema-automator/packages/importers.html#importing-from-owl) command from the [schema-automator repo](https://github.com/linkml/schema-automator). It requires the OWL input to be in the functional syntax. We recommend using [ROBOT](http://robot.obolibrary.org/) if you need to convert to functional syntax, but there are other options.

```shell
robot convert -i schemaorg.ttl -o schemaorg.ofn
schemauto import-owl schemaorg.ofn
```

**Comment by turbomam** [comment]
I'm not sure how closely this repo's issue tracker is monitored. For most of our repos, we suggest creating issues in [linkml/linkml](https://github.com/linkml/linkml/issues)

**Comment by joylix** [comment]
Thank you turbomam. I'll try it the way you say.
